name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [develop]

jobs:
  deploy-development:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/download-artifact@v5
        with:
          name: mfe-build
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}

      - run: echo "Deploying to development"

  deploy-staging:
    needs: deploy-development
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/download-artifact@v5
        with:
          name: mfe-build
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}

      - run: echo "Deploying to staging"

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/download-artifact@v5
        with:
          name: mfe-build
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}

      - run: echo "Deploying to production"
