name: CI

on:
  pull_request:
  push:
    branches: [develop]
jobs:
  deploy-development:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v3
        with:
          runtime: node@24
          cache: true
      - run: pnpm install --frozen-lockfile
      - run: pnpm exec turbo run build
      - name: Deploy
        run: |
          echo "Deploying MFE to development"
