name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/download-artifact@v8
        with:
          name: mfe-build
      - run: echo "Deploying to ${{ inputs.environment }}"
